[package]
name = "tron-startup"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
ratatui.workspace = true
tachyonfx.workspace = true
log.workspace = true
base64.workspace = true
tron-config.workspace = true
