[package]
name = "tron-font"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
fontique.workspace = true
swash.workspace = true
log.workspace = true
thiserror.workspace = true
harfrust.workspace = true
foldhash.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
objc2-core-foundation.workspace = true
objc2-core-text.workspace = true
