# 0x96f.
# From iTerm2-Color-Schemes by Mark Badolato and contributors (MIT).
foreground = "#fcfcfa"
background = "#262427"
cursor = "#fcfcfa"
cursor_text = "#000000"
selection_background = "#fcfcfa"
selection_foreground = "#262427"
normal = ["#262427", "#ff666d", "#b3e03a", "#ffc739", "#00cde8", "#a392e8", "#9deaf6", "#fcfcfa"]
bright = ["#545452", "#ff7e83", "#bee55e", "#ffd05e", "#1bd5eb", "#b0a3eb", "#acedf8", "#fcfcfa"]
