# Apple Classic.
# From iTerm2-Color-Schemes by Mark Badolato and contributors (MIT).
foreground = "#d5a200"
background = "#2c2b2b"
cursor = "#c7c7c7"
cursor_text = "#8c8c8c"
selection_background = "#6b5b02"
selection_foreground = "#67e000"
normal = ["#000000", "#c91b00", "#00c200", "#c7c400", "#1c3fe1", "#ca30c7", "#00c5c7", "#c7c7c7"]
bright = ["#686868", "#ff6e67", "#5ffa68", "#fffc67", "#6871ff", "#ff77ff", "#60fdff", "#ffffff"]
