# Ardoise.
# From iTerm2-Color-Schemes by Mark Badolato and contributors (MIT).
foreground = "#eaeaea"
background = "#1e1e1e"
cursor = "#f7f7f7"
cursor_text = "#000000"
selection_background = "#46515e"
selection_foreground = "#f1f3f5"
normal = ["#2c2c2c", "#d3322d", "#588b35", "#fca93a", "#2465c2", "#7332b4", "#64e1b8", "#f7f7f7"]
bright = ["#535353", "#fa5852", "#8dc252", "#ffea51", "#6ab5f8", "#be68ca", "#89ffdb", "#fefefe"]
