# Argonaut.
# From iTerm2-Color-Schemes by Mark Badolato and contributors (MIT).
foreground = "#fffaf4"
background = "#0e1019"
cursor = "#ff0018"
cursor_text = "#ff8ca4"
selection_background = "#002a3b"
selection_foreground = "#ffffff"
normal = ["#232323", "#ff000f", "#8ce10b", "#ffb900", "#008df8", "#6d43a6", "#00d8eb", "#ffffff"]
bright = ["#444444", "#ff2740", "#abe15b", "#ffd242", "#0092ff", "#9a5feb", "#67fff0", "#ffffff"]
