# Atom.
# From iTerm2-Color-Schemes by Mark Badolato and contributors (MIT).
foreground = "#c5c8c6"
background = "#161719"
cursor = "#d0d0d0"
cursor_text = "#151515"
selection_background = "#444444"
selection_foreground = "#c5c8c6"
normal = ["#000000", "#fd5ff1", "#87c38a", "#ffd7b1", "#85befd", "#b9b6fc", "#85befd", "#e0e0e0"]
bright = ["#4c4c4c", "#fd5ff1", "#94fa36", "#f5ffa8", "#96cbfe", "#b9b6fc", "#85befd", "#e0e0e0"]
