# Aurora.
# From iTerm2-Color-Schemes by Mark Badolato and contributors (MIT).
foreground = "#ffca28"
background = "#23262e"
cursor = "#ee5d43"
cursor_text = "#ffd29c"
selection_background = "#292e38"
selection_foreground = "#00e8c6"
normal = ["#23262e", "#f0266f", "#8fd46d", "#ffe66d", "#102ee4", "#ee5d43", "#03d6b8", "#c74ded"]
bright = ["#4f545e", "#f92672", "#8fd46d", "#ffe66d", "#03d6b8", "#ee5d43", "#03d6b8", "#c74ded"]
