# Ayu Mirage.
# From iTerm2-Color-Schemes by Mark Badolato and contributors (MIT).
foreground = "#cccac2"
background = "#1f2430"
cursor = "#ffcc66"
cursor_text = "#1f2430"
selection_background = "#409fff"
selection_foreground = "#1f2430"
normal = ["#171b24", "#ed8274", "#87d96c", "#facc6e", "#6dcbfa", "#dabafa", "#90e1c6", "#c7c7c7"]
bright = ["#686868", "#f28779", "#d5ff80", "#ffd173", "#73d0ff", "#dfbfff", "#95e6cb", "#ffffff"]
