# Ayu.
# From iTerm2-Color-Schemes by Mark Badolato and contributors (MIT).
foreground = "#bfbdb6"
background = "#0b0e14"
cursor = "#e6b450"
cursor_text = "#0b0e14"
selection_background = "#409fff"
selection_foreground = "#0b0e14"
normal = ["#11151c", "#ea6c73", "#7fd962", "#f9af4f", "#53bdfa", "#cda1fa", "#90e1c6", "#c7c7c7"]
bright = ["#686868", "#f07178", "#aad94c", "#ffb454", "#59c2ff", "#d2a6ff", "#95e6cb", "#ffffff"]
