# Belafonte Night.
# From iTerm2-Color-Schemes by Mark Badolato and contributors (MIT).
foreground = "#968c83"
background = "#20111b"
cursor = "#968c83"
cursor_text = "#20111b"
selection_background = "#45373c"
selection_foreground = "#968c83"
normal = ["#20111b", "#be100e", "#858162", "#eaa549", "#426a79", "#97522c", "#989a9c", "#968c83"]
bright = ["#5e5252", "#be100e", "#858162", "#eaa549", "#426a79", "#97522c", "#989a9c", "#d5ccba"]
