# Blue Matrix.
# From iTerm2-Color-Schemes by Mark Badolato and contributors (MIT).
foreground = "#00a2ff"
background = "#101116"
cursor = "#76ff9f"
cursor_text = "#a6a6a6"
selection_background = "#c1deff"
selection_foreground = "#000000"
normal = ["#101116", "#ff5680", "#00ff9c", "#fffc58", "#00b0ff", "#d57bff", "#76c1ff", "#c7c7c7"]
bright = ["#686868", "#ff6e67", "#5ffa68", "#fffc67", "#6871ff", "#d682ec", "#60fdff", "#ffffff"]
