# Blue Dolphin.
# From iTerm2-Color-Schemes by Mark Badolato and contributors (MIT).
foreground = "#c5f2ff"
background = "#006984"
cursor = "#ffcc00"
cursor_text = "#292d3e"
selection_background = "#2baeca"
selection_foreground = "#eceff1"
normal = ["#292d3e", "#ff8288", "#b4e88d", "#f4d69f", "#82aaff", "#e9c1ff", "#89ebff", "#d0d0d0"]
bright = ["#9094a4", "#ff8b92", "#ddffa7", "#ffe585", "#9cc4ff", "#ddb0f6", "#a3f7ff", "#ffffff"]
