# Borland.
# From iTerm2-Color-Schemes by Mark Badolato and contributors (MIT).
foreground = "#ffff4e"
background = "#0000a4"
cursor = "#ffa560"
cursor_text = "#ffffff"
selection_background = "#a4a4a4"
selection_foreground = "#0000a4"
normal = ["#4f4f4f", "#ff6c60", "#a8ff60", "#ffffb6", "#96cbfe", "#ff73fd", "#c6c5fe", "#eeeeee"]
bright = ["#7c7c7c", "#ffb6b0", "#ceffac", "#ffffcc", "#b5dcff", "#ff9cfe", "#dfdffe", "#ffffff"]
