# Coffee Theme.
# From iTerm2-Color-Schemes by Mark Badolato and contributors (MIT).
foreground = "#000000"
background = "#f5deb3"
cursor = "#a1a1a1"
cursor_text = "#fffc67"
selection_background = "#c1deff"
selection_foreground = "#000000"
normal = ["#000000", "#c91b00", "#00c200", "#adaa00", "#0225c7", "#ca30c7", "#00b8ba", "#a1a1a1"]
bright = ["#686868", "#ff6e67", "#1fba28", "#b2af1b", "#6871ff", "#f26af2", "#20bdbf", "#ffffff"]
