# Duckbones.
# From iTerm2-Color-Schemes by Mark Badolato and contributors (MIT).
foreground = "#ebefc0"
background = "#0e101a"
cursor = "#edf2c2"
cursor_text = "#0e101a"
selection_background = "#37382d"
selection_foreground = "#ebefc0"
normal = ["#0e101a", "#e03600", "#5dcd97", "#e39500", "#00a3cb", "#795ccc", "#00a3cb", "#ebefc0"]
bright = ["#444860", "#ff4821", "#58db9e", "#f6a100", "#00b4e0", "#b3a1e6", "#00b4e0", "#b3b692"]
