# Embark.
# From iTerm2-Color-Schemes by Mark Badolato and contributors (MIT).
foreground = "#eeffff"
background = "#1e1c31"
cursor = "#a1efd3"
cursor_text = "#1e1c31"
selection_background = "#fbfcfc"
selection_foreground = "#1e1c31"
normal = ["#1e1c31", "#f0719b", "#a1efd3", "#ffe9aa", "#57c7ff", "#c792ea", "#87dfeb", "#f8f8f2"]
bright = ["#585273", "#f02e6e", "#2ce592", "#ffb378", "#1da0e2", "#a742ea", "#63f2f1", "#a6b3cc"]
