# Espresso Libre.
# From iTerm2-Color-Schemes by Mark Badolato and contributors (MIT).
foreground = "#b8a898"
background = "#2a211c"
cursor = "#ffffff"
cursor_text = "#000000"
selection_background = "#c3dcff"
selection_foreground = "#ab9b8b"
normal = ["#000000", "#cc0000", "#1a921c", "#f0e53a", "#0066ff", "#c5656b", "#06989a", "#d3d7cf"]
bright = ["#555753", "#ef2929", "#9aff87", "#fffb5c", "#43a8ed", "#ff818a", "#34e2e2", "#eeeeec"]
