# Fairyfloss.
# From iTerm2-Color-Schemes by Mark Badolato and contributors (MIT).
foreground = "#f8f8f2"
background = "#5a5475"
cursor = "#f8f8f0"
cursor_text = "#060709"
selection_background = "#8077a8"
selection_foreground = "#f6e1ce"
normal = ["#040303", "#f92672", "#c2ffdf", "#e6c000", "#c2ffdf", "#ffb8d1", "#c5a3ff", "#f8f8f0"]
bright = ["#6090cb", "#ff857f", "#c2ffdf", "#ffea00", "#c2ffdf", "#ffb8d1", "#c5a3ff", "#f8f8f0"]
