# Fish Tank.
# From iTerm2-Color-Schemes by Mark Badolato and contributors (MIT).
foreground = "#ecf0fe"
background = "#232537"
cursor = "#fecd5e"
cursor_text = "#232537"
selection_background = "#fcf7e9"
selection_foreground = "#232537"
normal = ["#03073c", "#c6004a", "#acf157", "#fecd5e", "#525fb8", "#986f82", "#968763", "#ecf0fc"]
bright = ["#6c5b30", "#da4b8a", "#dbffa9", "#fee6a9", "#b2befa", "#fda5cd", "#a5bd86", "#f6ffec"]
