# GitHub Dark Dimmed.
# From iTerm2-Color-Schemes by Mark Badolato and contributors (MIT).
foreground = "#adbac7"
background = "#22272e"
cursor = "#539bf5"
cursor_text = "#93dbff"
selection_background = "#adbac7"
selection_foreground = "#22272e"
normal = ["#545d68", "#f47067", "#57ab5a", "#c69026", "#539bf5", "#b083f0", "#39c5cf", "#909dab"]
bright = ["#636e7b", "#ff938a", "#6bc46d", "#daaa3f", "#6cb6ff", "#dcbdfb", "#56d4dd", "#cdd9e5"]
