# GitHub Dark Colorblind.
# From iTerm2-Color-Schemes by Mark Badolato and contributors (MIT).
foreground = "#c9d1d9"
background = "#0d1117"
cursor = "#58a6ff"
cursor_text = "#98e6ff"
selection_background = "#c9d1d9"
selection_foreground = "#0d1117"
normal = ["#484f58", "#ec8e2c", "#58a6ff", "#d29922", "#58a6ff", "#bc8cff", "#39c5cf", "#b1bac4"]
bright = ["#6e7681", "#fdac54", "#79c0ff", "#e3b341", "#79c0ff", "#d2a8ff", "#56d4dd", "#ffffff"]
