# GitHub Light High Contrast.
# From iTerm2-Color-Schemes by Mark Badolato and contributors (MIT).
foreground = "#0e1116"
background = "#ffffff"
cursor = "#0349b4"
cursor_text = "#367ce7"
selection_background = "#0e1116"
selection_foreground = "#ffffff"
normal = ["#0e1116", "#a0111f", "#024c1a", "#3f2200", "#0349b4", "#622cbc", "#1b7c83", "#66707b"]
bright = ["#4b535d", "#86061d", "#055d20", "#4e2c00", "#1168e3", "#844ae7", "#3192aa", "#88929d"]
