# Gruvbox Light Hard.
# From iTerm2-Color-Schemes by Mark Badolato and contributors (MIT).
foreground = "#3c3836"
background = "#f9f5d7"
cursor = "#3c3836"
cursor_text = "#f9f5d7"
selection_background = "#3c3836"
selection_foreground = "#f9f5d7"
normal = ["#f9f5d7", "#cc241d", "#98971a", "#d79921", "#458588", "#b16286", "#689d6a", "#7c6f64"]
bright = ["#928374", "#9d0006", "#79740e", "#b57614", "#076678", "#8f3f71", "#427b58", "#3c3836"]
