# Gruvbox Dark Hard.
# From iTerm2-Color-Schemes by Mark Badolato and contributors (MIT).
foreground = "#ebdbb2"
background = "#1d2021"
cursor = "#ebdbb2"
cursor_text = "#1d2021"
selection_background = "#665c54"
selection_foreground = "#ebdbb2"
normal = ["#1d2021", "#cc241d", "#98971a", "#d79921", "#458588", "#b16286", "#689d6a", "#a89984"]
bright = ["#928374", "#fb4934", "#b8bb26", "#fabd2f", "#83a598", "#d3869b", "#8ec07c", "#ebdbb2"]
