# Hacktober.
# From iTerm2-Color-Schemes by Mark Badolato and contributors (MIT).
foreground = "#c9c9c9"
background = "#141414"
cursor = "#c9c9c9"
cursor_text = "#141414"
selection_background = "#141414"
selection_foreground = "#c9c9c9"
normal = ["#191918", "#b34538", "#587744", "#d08949", "#206ec5", "#864651", "#ac9166", "#f1eee7"]
bright = ["#464444", "#b33323", "#42824a", "#c75a22", "#5389c5", "#e795a5", "#ebc587", "#ffffff"]
