# Homebrew.
# From iTerm2-Color-Schemes by Mark Badolato and contributors (MIT).
foreground = "#00ff00"
background = "#000000"
cursor = "#23ff18"
cursor_text = "#ff0018"
selection_background = "#083905"
selection_foreground = "#ffffff"
normal = ["#000000", "#990000", "#00a600", "#999900", "#0d0dbf", "#b200b2", "#00a6b2", "#bfbfbf"]
bright = ["#666666", "#e50000", "#00d900", "#e5e500", "#0000ff", "#e500e5", "#00e5e5", "#e5e5e5"]
