# Horizon.
# From iTerm2-Color-Schemes by Mark Badolato and contributors (MIT).
foreground = "#d5d8da"
background = "#1c1e26"
cursor = "#6c6f93"
cursor_text = "#9fa2c6"
selection_background = "#6c6f93"
selection_foreground = "#1c1e26"
normal = ["#000000", "#e95678", "#29d398", "#fab795", "#26bbd9", "#ee64ac", "#59e1e3", "#e5e5e5"]
bright = ["#666666", "#ec6a88", "#3fdaa4", "#fbc3a7", "#3fc4de", "#f075b5", "#6be4e6", "#e5e5e5"]
