# IBM 5153 CGA.
# From iTerm2-Color-Schemes by Mark Badolato and contributors (MIT).
foreground = "#cecece"
background = "#141414"
cursor = "#cecece"
cursor_text = "#141414"
selection_background = "#cecece"
selection_foreground = "#141414"
normal = ["#141414", "#d03333", "#1bd01b", "#d08c1b", "#1b1bd0", "#d01bd0", "#1bd0d0", "#cecece"]
bright = ["#4e4e4e", "#dc4e4e", "#4edc4e", "#f3f34e", "#4e4edc", "#f34ef3", "#4ef3f3", "#ffffff"]
