# iTerm2 Solarized Light.
# From iTerm2-Color-Schemes by Mark Badolato and contributors (MIT).
foreground = "#657b83"
background = "#fdf6e3"
cursor = "#657b83"
cursor_text = "#eee8d5"
selection_background = "#eee8d5"
selection_foreground = "#586e75"
normal = ["#073642", "#dc322f", "#859900", "#b58900", "#268bd2", "#d33682", "#2aa198", "#bbb5a2"]
bright = ["#002b36", "#cb4b16", "#586e75", "#657b83", "#839496", "#6c71c4", "#93a1a1", "#fdf6e3"]
