# Jackie Brown.
# From iTerm2-Color-Schemes by Mark Badolato and contributors (MIT).
foreground = "#ffcc2f"
background = "#2c1d16"
cursor = "#23ff18"
cursor_text = "#ff0018"
selection_background = "#af8d21"
selection_foreground = "#ffffff"
normal = ["#2c1d16", "#ef5734", "#2baf2b", "#bebf00", "#246eb2", "#d05ec1", "#00acee", "#bfbfbf"]
bright = ["#666666", "#e50000", "#86a93e", "#e5e500", "#0000ff", "#e500e5", "#00e5e5", "#e5e5e5"]
