# Kolorit.
# From iTerm2-Color-Schemes by Mark Badolato and contributors (MIT).
foreground = "#efecec"
background = "#1d1a1e"
cursor = "#c7c7c7"
cursor_text = "#8c8c8c"
selection_background = "#e1925c"
selection_foreground = "#1d1a1e"
normal = ["#1d1a1e", "#ff5b82", "#47d7a1", "#e8e562", "#5db4ee", "#da6cda", "#57e9eb", "#ededed"]
bright = ["#504d51", "#ff5b82", "#47d7a1", "#e8e562", "#5db4ee", "#da6cda", "#57e9eb", "#ededed"]
