# Miasma.
# From iTerm2-Color-Schemes by Mark Badolato and contributors (MIT).
foreground = "#c2c2b0"
background = "#222222"
cursor = "#c7c7c7"
cursor_text = "#959595"
selection_background = "#e5c47b"
selection_foreground = "#000000"
normal = ["#000000", "#685742", "#5f875f", "#b36d43", "#78824b", "#bb7744", "#c9a554", "#d7c483"]
bright = ["#666666", "#685742", "#5f875f", "#b36d43", "#78824b", "#bb7744", "#c9a554", "#d7c483"]
