# Monokai Pro Machine.
# From iTerm2-Color-Schemes by Mark Badolato and contributors (MIT).
foreground = "#f2fffc"
background = "#273136"
cursor = "#b8c4c3"
cursor_text = "#859190"
selection_background = "#545f62"
selection_foreground = "#f2fffc"
normal = ["#273136", "#ff6d7e", "#a2e57b", "#ffed72", "#ffb270", "#baa0f8", "#7cd5f1", "#f2fffc"]
bright = ["#6b7678", "#ff6d7e", "#a2e57b", "#ffed72", "#ffb270", "#baa0f8", "#7cd5f1", "#f2fffc"]
