# Oceanic Next.
# From iTerm2-Color-Schemes by Mark Badolato and contributors (MIT).
foreground = "#c0c5ce"
background = "#162c35"
cursor = "#c0c5ce"
cursor_text = "#1b2b34"
selection_background = "#4f5b66"
selection_foreground = "#c0c5ce"
normal = ["#162c35", "#ec5f67", "#99c794", "#fac863", "#6699cc", "#c594c5", "#5fb3b3", "#ffffff"]
bright = ["#65737e", "#ec5f67", "#99c794", "#fac863", "#6699cc", "#c594c5", "#5fb3b3", "#ffffff"]
