# One Dark.
foreground = "#abb2bf"
background = "#282c34"
cursor = "#528bff"
selection_background = "#3e4451"
normal = ["#282c34", "#e06c75", "#98c379", "#e5c07b", "#61afef", "#c678dd", "#56b6c2", "#abb2bf"]
bright = ["#5c6370", "#e06c75", "#98c379", "#e5c07b", "#61afef", "#c678dd", "#56b6c2", "#ffffff"]
