# Raycast Dark.
# From iTerm2-Color-Schemes by Mark Badolato and contributors (MIT).
foreground = "#ffffff"
background = "#1a1a1a"
cursor = "#cccccc"
cursor_text = "#999999"
selection_background = "#333333"
selection_foreground = "#595959"
normal = ["#000000", "#ff5360", "#59d499", "#ffc531", "#56c2ff", "#cf2f98", "#52eee5", "#ffffff"]
bright = ["#4c4c4c", "#ff6363", "#59d499", "#ffc531", "#56c2ff", "#cf2f98", "#52eee5", "#ffffff"]
