# Relaxed.
# From iTerm2-Color-Schemes by Mark Badolato and contributors (MIT).
foreground = "#d9d9d9"
background = "#353a44"
cursor = "#d9d9d9"
cursor_text = "#1b1b1b"
selection_background = "#6a7985"
selection_foreground = "#d9d9d9"
normal = ["#151515", "#bc5653", "#909d63", "#ebc17a", "#6a8799", "#b06698", "#c9dfff", "#d9d9d9"]
bright = ["#636363", "#bc5653", "#a0ac77", "#ebc17a", "#7eaac7", "#b06698", "#acbbd0", "#f7f7f7"]
