# Sea Shells.
# From iTerm2-Color-Schemes by Mark Badolato and contributors (MIT).
foreground = "#deb88d"
background = "#09141b"
cursor = "#fca02f"
cursor_text = "#08131a"
selection_background = "#1e4962"
selection_foreground = "#fee4ce"
normal = ["#17384c", "#d15123", "#027c9b", "#fca02f", "#1e4950", "#68d4f1", "#50a3b5", "#deb88d"]
bright = ["#434b53", "#d48678", "#628d98", "#fdd39f", "#1bbcdd", "#bbe3ee", "#87acb4", "#fee4ce"]
