# Sugarplum.
# From iTerm2-Color-Schemes by Mark Badolato and contributors (MIT).
foreground = "#db7ddd"
background = "#111147"
cursor = "#53b397"
cursor_text = "#93f3d7"
selection_background = "#5ca8dc"
selection_foreground = "#ead8ff"
normal = ["#111147", "#5ca8dc", "#53b397", "#249a84", "#db7ddd", "#d0beee", "#f9f3f9", "#a175d4"]
bright = ["#44447a", "#5cb5dc", "#52deb5", "#01f5c7", "#fa5dfd", "#c6a5fd", "#ffffff", "#b577fd"]
