# Tomorrow Night Eighties.
# From iTerm2-Color-Schemes by Mark Badolato and contributors (MIT).
foreground = "#cccccc"
background = "#2d2d2d"
cursor = "#cccccc"
cursor_text = "#2d2d2d"
selection_background = "#515151"
selection_foreground = "#cccccc"
normal = ["#000000", "#f2777a", "#99cc99", "#ffcc66", "#6699cc", "#cc99cc", "#66cccc", "#ffffff"]
bright = ["#595959", "#f2777a", "#99cc99", "#ffcc66", "#6699cc", "#cc99cc", "#66cccc", "#ffffff"]
