# Tomorrow Night.
# From iTerm2-Color-Schemes by Mark Badolato and contributors (MIT).
foreground = "#c5c8c6"
background = "#1d1f21"
cursor = "#c5c8c6"
cursor_text = "#1d1f21"
selection_background = "#373b41"
selection_foreground = "#c5c8c6"
normal = ["#000000", "#cc6666", "#b5bd68", "#f0c674", "#81a2be", "#b294bb", "#8abeb7", "#ffffff"]
bright = ["#4c4c4c", "#cc6666", "#b5bd68", "#f0c674", "#81a2be", "#b294bb", "#8abeb7", "#ffffff"]
