# Twilight.
# From iTerm2-Color-Schemes by Mark Badolato and contributors (MIT).
foreground = "#ffffd4"
background = "#141414"
cursor = "#ffffff"
cursor_text = "#000000"
selection_background = "#313131"
selection_foreground = "#ffffd4"
normal = ["#141414", "#c06d44", "#afb97a", "#c2a86c", "#44474a", "#b4be7c", "#778385", "#ffffd4"]
bright = ["#404040", "#de7c4c", "#ccd88c", "#e2c47e", "#5a5e62", "#d0dc8e", "#8a989b", "#ffffd4"]
