# urban.
# From iTerm2-Color-Schemes by Mark Badolato and contributors (MIT).
foreground = "#c0a79a"
background = "#312e39"
cursor = "#c0a79a"
cursor_text = "#312e39"
selection_background = "#c0a79a"
selection_foreground = "#312e39"
normal = ["#33303b", "#87404f", "#74934e", "#ae835a", "#615772", "#854b64", "#625464", "#c0a79a"]
bright = ["#5c5865", "#87404f", "#74934e", "#ae835a", "#615772", "#854b64", "#625464", "#c0a79a"]
