# Vague.
# From iTerm2-Color-Schemes by Mark Badolato and contributors (MIT).
foreground = "#cdcdcd"
background = "#141415"
cursor = "#cdcdcd"
cursor_text = "#141415"
selection_background = "#252530"
selection_foreground = "#cdcdcd"
normal = ["#252530", "#d8647e", "#7fa563", "#f3be7c", "#6e94b2", "#bb9dbd", "#aeaed1", "#cdcdcd"]
bright = ["#606079", "#e08398", "#99b782", "#f5cb96", "#8ba9c1", "#c9b1ca", "#bebeda", "#d7d7d7"]
