# Warm Neon.
# From iTerm2-Color-Schemes by Mark Badolato and contributors (MIT).
foreground = "#afdab6"
background = "#404040"
cursor = "#30ff24"
cursor_text = "#0bbc04"
selection_background = "#b0ad21"
selection_foreground = "#ffffff"
normal = ["#000000", "#e24346", "#39b13a", "#dae145", "#4261c5", "#f920fb", "#2abbd4", "#d0b8a3"]
bright = ["#fefcfc", "#e97071", "#9cc090", "#ddda7a", "#7b91d6", "#f674ba", "#5ed1e5", "#d8c8bb"]
