[package]
name = "tron-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4.13"
tron-core = { path = "../crates/tron-core" }

[[bin]]
name = "terminal"
path = "fuzz_targets/terminal.rs"
test = false
doc = false
bench = false

[workspace]
members = ["."]
