[package]
name = "tron-inspect"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
tron-core.workspace = true
tron-render.workspace = true
egui.workspace = true
egui-wgpu.workspace = true
wgpu.workspace = true
winit.workspace = true
log.workspace = true
